name: real-time-da
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py=3.14
  - ipykernel=6.30
  - ipywidgets=8.1
  - jupyter=1.1
  - matplotlib=3.9
  - multiprocess=0.70
  - numba=0.60
  - numpy=2.0
  - pip=25.2
  - pyts=0.13
  - pytest=8.4
  - requests=2.32
  - scikit-optimize=0.10
  - scipy=1.13
  - seaborn=0.13
  - tabulate=0.9
  - tqdm=4.67
  - pip:
    - ipython-genutils~=0.2
    - modulo-vki==2.1
    - pyqt5~=5.15