name: real-time-da
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - scikit-optimize
  - multiprocess
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - ipywidgets
  - h5py
  - tqdm
  - requests
  - tabulate
  - pyts
  - pip
  - pip:
      - ipython-genutils
      - modulo-vki
      - pyqt5
